<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>nl.eur.pdpot</groupId>
		<artifactId>pdpot</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>pdpot-visualizer</artifactId>

	

	<dependencies>
        <dependency>
            <groupId>nl.eur.pdpot</groupId>
            <artifactId>pdpot-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>nl.eur.pdpot</groupId>
            <artifactId>pdpot-assign</artifactId>
            <version>${project.version}</version>
        </dependency>
		<dependency>
		    <groupId>org.thymeleaf</groupId>
		    <artifactId>thymeleaf</artifactId>
		    <version>${thymeleaf.version}</version> <!-- Or latest -->
		</dependency>
		<dependency>
			<groupId>info.picocli</groupId>
			<artifactId>picocli</artifactId>
			<version>${picocli.version}</version>
		</dependency>
		<dependency>
			<groupId>me.tongfei</groupId>
			<artifactId>progressbar</artifactId>
			<version>${progressbar.version}</version>
		</dependency>
		<dependency>
			<groupId>com.madgag</groupId>
			<artifactId>animated-gif-lib</artifactId>
			<version>1.4</version>
		</dependency>
	</dependencies>

</project>