<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>nl.eur.pdpot</groupId>
        <artifactId>pdpot</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>pdpot-assign</artifactId>

    <dependencies>
        <dependency>
            <groupId>nl.eur.pdpot</groupId>
            <artifactId>pdpot-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.ortools</groupId>
            <artifactId>ortools-java</artifactId>
            <version>${google.ortools.version}</version>
        </dependency>
    </dependencies>


</project>