<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.pdpot</groupId>
		<artifactId>pdpot</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<artifactId>pdpot-visualizer-video</artifactId>

	<dependencies>
        <dependency>
            <groupId>org.pdpot</groupId>
            <artifactId>pdpot-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.pdpot</groupId>
            <artifactId>pdpot-visualizer</artifactId>
            <version>${project.version}</version>
        </dependency>
		<dependency>
			<groupId>org.bytedeco</groupId>
			<artifactId>javacv-platform</artifactId>
			<version>${javacv.version}</version>
		</dependency>
		<dependency>
			<groupId>info.picocli</groupId>
			<artifactId>picocli</artifactId>
			<version>${picocli.version}</version>
		</dependency>
	</dependencies>

</project>